/**
 * icon-app icon set component.
 * Usage: <icon-app name="icon-name" size={20} color="#4F8EF7" />
 */

import createIconSet from 'react-native-vector-icons/lib/create-icon-set';
const glyphMap = {
  'ic-attach': 98,
  'ic-camera': 100,
  'ic-camera-fill': 101,
  'ic-card': 102,
  'ic-card-holder': 103,
  'ic-caret-down': 104,
  'ic-caret-left': 105,
  'ic-caret-right': 106,
  'ic-caret-up': 107,
  'ic-change': 108,
  'ic-chat': 109,
  'ic-chat-fill': 110,
  'ic-check-deliver': 111,
  'ic-checked': 112,
  'ic-close': 113,
  'ic-close-without-circle': 115,
  'ic-contact': 116,
  'ic-curent-location': 117,
  'ic-done': 121,
  'ic-edit': 122,
  'ic-email': 65,
  'ic-error': 66,
  'ic-eye-fill': 68,
  'ic-facebook-fill': 69,
  'ic-fast': 70,
  'ic-funnel': 71,
  'ic-help-wheel': 72,
  'ic-history-fill': 73,
  'ic-homepage': 74,
  'ic-information': 75,
  'ic-map-fill': 76,
  'ic-menu': 77,
  'ic-money': 78,
  'ic-notification': 79,
  'ic-order-done': 80,
  'ic-package-fill': 81,
  'ic-package-fill-2': 82,
  'ic-phone': 83,
  'ic-pin-fill': 84,
  'ic-plus': 85,
  'ic-privacy-policy': 86,
  'ic-question': 87,
  'ic-re-order': 88,
  'ic-saved': 89,
  'ic-saved-1': 90,
  'ic-selfie': 49,
  'ic-send': 50,
  'ic-setting': 51,
  'ic-setting-fill': 52,
  'ic-share-fill': 53,
  'ic-star': 55,
  'ic-support-fill': 56,
  'ic-term-condition': 57,
  'ic-ticket-1': 33,
  'ic-ticket-2': 34,
  'ic-time': 35,
  'ic-update': 36,
  'ic-wallet': 37,
  'ic-calendar': 99,
  'ic-add-favourite-fill': 97,
  'ic-close-fill': 114,
  'ic-deliver-done': 118,
  'ic-eye-close-fill': 119,
  'ic-search': 120,
  'ic-slash': 67,
  'ic-message': 48,
  'ic-map': 54,
};

const iconSet: any = createIconSet(glyphMap, 'icon-app', 'icon-app.ttf');

export default iconSet;
export const { Button, getImageSource, getImageSourceSync } = iconSet;
